//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActualizacionPedidos
    {
        public int IdActualizacionPedidos { get; set; }
        public Nullable<int> IdPedido { get; set; }
        public Nullable<int> IdEstadoPedido { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual Direccion Direccion { get; set; }
        public virtual EstadoPedido EstadoPedido { get; set; }
    }
}
