//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedidos()
        {
            this.DetallePedido = new HashSet<DetallePedido>();
        }
    
        public int IdPedido { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public Nullable<byte> IdTipoPago { get; set; }
        public Nullable<int> IdDireccion { get; set; }
        public Nullable<int> IdEstadoPedido { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> IdRepartidor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePedido> DetallePedido { get; set; }
        public virtual Direccion Direccion { get; set; }
        public virtual EstadoPedido EstadoPedido { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Repartidor Repartidor { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoPago TipoPago { get; set; }
    }
}
