//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMartinezTestWebServices.ServiceReferenceDemo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDemo.IOperaciones")]
    public interface IOperaciones {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Suma", ReplyAction="http://tempuri.org/IOperaciones/SumaResponse")]
        int Suma(int numero1, int numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Suma", ReplyAction="http://tempuri.org/IOperaciones/SumaResponse")]
        System.Threading.Tasks.Task<int> SumaAsync(int numero1, int numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Resta", ReplyAction="http://tempuri.org/IOperaciones/RestaResponse")]
        int Resta(int numero1, int numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Resta", ReplyAction="http://tempuri.org/IOperaciones/RestaResponse")]
        System.Threading.Tasks.Task<int> RestaAsync(int numero1, int numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Multiplicacion", ReplyAction="http://tempuri.org/IOperaciones/MultiplicacionResponse")]
        int Multiplicacion(int numero1, int numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Multiplicacion", ReplyAction="http://tempuri.org/IOperaciones/MultiplicacionResponse")]
        System.Threading.Tasks.Task<int> MultiplicacionAsync(int numero1, int numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Division", ReplyAction="http://tempuri.org/IOperaciones/DivisionResponse")]
        int Division(int numero1, int numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Division", ReplyAction="http://tempuri.org/IOperaciones/DivisionResponse")]
        System.Threading.Tasks.Task<int> DivisionAsync(int numero1, int numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Potencia", ReplyAction="http://tempuri.org/IOperaciones/PotenciaResponse")]
        int Potencia(int numero1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaciones/Potencia", ReplyAction="http://tempuri.org/IOperaciones/PotenciaResponse")]
        System.Threading.Tasks.Task<int> PotenciaAsync(int numero1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOperacionesChannel : CMartinezTestWebServices.ServiceReferenceDemo.IOperaciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperacionesClient : System.ServiceModel.ClientBase<CMartinezTestWebServices.ServiceReferenceDemo.IOperaciones>, CMartinezTestWebServices.ServiceReferenceDemo.IOperaciones {
        
        public OperacionesClient() {
        }
        
        public OperacionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperacionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperacionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperacionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Suma(int numero1, int numero2) {
            return base.Channel.Suma(numero1, numero2);
        }
        
        public System.Threading.Tasks.Task<int> SumaAsync(int numero1, int numero2) {
            return base.Channel.SumaAsync(numero1, numero2);
        }
        
        public int Resta(int numero1, int numero2) {
            return base.Channel.Resta(numero1, numero2);
        }
        
        public System.Threading.Tasks.Task<int> RestaAsync(int numero1, int numero2) {
            return base.Channel.RestaAsync(numero1, numero2);
        }
        
        public int Multiplicacion(int numero1, int numero2) {
            return base.Channel.Multiplicacion(numero1, numero2);
        }
        
        public System.Threading.Tasks.Task<int> MultiplicacionAsync(int numero1, int numero2) {
            return base.Channel.MultiplicacionAsync(numero1, numero2);
        }
        
        public int Division(int numero1, int numero2) {
            return base.Channel.Division(numero1, numero2);
        }
        
        public System.Threading.Tasks.Task<int> DivisionAsync(int numero1, int numero2) {
            return base.Channel.DivisionAsync(numero1, numero2);
        }
        
        public int Potencia(int numero1) {
            return base.Channel.Potencia(numero1);
        }
        
        public System.Threading.Tasks.Task<int> PotenciaAsync(int numero1) {
            return base.Channel.PotenciaAsync(numero1);
        }
    }
}
